# API key vem de variável de ambiente, NUNCA escrita aqui
quarkus.langchain4j.ai.gemini.api-key=${GEMINI_API_KEY}

quarkus.langchain4j.ai.gemini.chat-model.model-id=gemini-3.8-flash
quarkus.langchain4j.ai.gemini.chat-model.timeout=60s

quarkus.langchain4j.ai.gemini.embedding-model.model-id=gemini-embedding-001
quarkus.langchain4j.ai.gemini.embedding-model.output-dimension=768
quarkus.langchain4j.ai.gemini.embedding-model.timeout=60s

quarkus.langchain4j.pgvector.register-vector-pg-extension=true
quarkus.langchain4j.pgvector.dimension=768
quarkus.langchain4j.pgvector.table=travel_embeddings_gemini
quarkus.langchain4j.pgvector.drop-table-first=true

quarkus.langchain4j.ai.gemini.chat-model.log-requests=true
quarkus.langchain4j.ai.gemini.chat-model.log-responses=true